leaned up some of my code
Signed-off-by: The-Repo-Club <wayne6324@gmail.com>

diff --git a/proctl b/proctl
--- a/proctl
+++ b/proctl
@@ -5,7 +5,7 @@
 # GitHub		- https://github.com/The-Repo-Club/
 # Author		- The-Repo-Club [wayne6324@gmail.com]
 # Start On		- Fri 18 February 2022, 07:26:28 pm (GMT)
-# Modified On	- Tue 22 February 2022, 09:58:45 pm (GMT) 
+# Modified On	- Tue 22 February 2022, 10:49:20 pm (GMT) 
 # -------------------------------------------------------------------------
 #
 #
@@ -127,23 +127,23 @@ make_new_config() {
 	#=== DEFAULT CONFIG ===========================================================
 
 	read -d '' <<-EOF
-		#!/usr/bin/env sh
-		export AUTHOR_NAME='$(git config user.name || echo "${USER}")'
-		export AUTHOR_EMAIL='$(git config user.email || echo "${USER}@gmail.com")'
-		export AUTHOR_WEBSITE='https://example.com/'
-		export AUTHOR_GIT='http://github.com/$(git config user.name || echo "${USER}")'
-		export LICENSE_DIR='$LICENSE_DIR'
+	#!/usr/bin/env sh
+	export AUTHOR_NAME='$(git config user.name || echo "${USER}")'
+	export AUTHOR_EMAIL='$(git config user.email || echo "${USER}@gmail.com")'
+	export AUTHOR_WEBSITE='https://example.com/'
+	export AUTHOR_GIT='http://github.com/$(git config user.name || echo "${USER}")'
+	export LICENSE_DIR='$LICENSE_DIR'
 	EOF
 
 	echo "$REPLY" >"$LICENSE_CONF"
 
 	read -d '' <<-EOF
-		#!/usr/bin/env sh
-		export AUTHOR_NAME='$(git config user.name || echo "${USER}")'
-		export AUTHOR_EMAIL='$(git config user.email || echo "${USER}@gmail.com")'
-		export AUTHOR_WEBSITE='https://example.com/'
-		export AUTHOR_GIT='http://github.com/$(git config user.name || echo "${USER}")'
-		export LANGUAGE_DIR='$LANGUAGE_DIR'
+	#!/usr/bin/env sh
+	export AUTHOR_NAME='$(git config user.name || echo "${USER}")'
+	export AUTHOR_EMAIL='$(git config user.email || echo "${USER}@gmail.com")'
+	export AUTHOR_WEBSITE='https://example.com/'
+	export AUTHOR_GIT='http://github.com/$(git config user.name || echo "${USER}")'
+	export LANGUAGE_DIR='$LANGUAGE_DIR'
 	EOF
 
 	echo "$REPLY" >"$LANGUAGE_CONF"
@@ -197,8 +197,13 @@ initialize_repo() {
 
 check_valid_license() {
 	lic="$(echo "$1" | sed "$LICENSE_SED")"
-	echo "$1" | grep -qi '^@' || (error "License '$lic' is not valid" && exit 9)
-	[[ ! -f "$LICENSE_DIR"/"$lic" ]] && (error "License '$lic' does not exist" && exit 10)
+	if [[ $1 != \@* ]]; then
+		error "License '$lic' is not valid"
+		exit 9
+	elif ! [[ -f $LICENSE_DIR/$lic ]]; then
+		error "License '$lic' does not exist"
+		exit 10
+	fi
 
 	return 0
 }
@@ -210,8 +215,13 @@ check_valid_license() {
 
 check_valid_language() {
 	lang="$(echo "$1" | sed "$LANGUAGE_SED")"
-	echo "$1" | grep -qi '^@' || (error "Language '$lang' is not valid" && exit 9)
-	[[ ! -f "$LANGUAGE_DIR"/"$lang" ]] && (error "Language '$lang' does not exist" && exit 10)
+	if [[ $1 != \@* ]]; then
+		error "License '$lang' is not valid"
+		exit 9
+	elif ! [[ -f $LANGUAGE_DIR/$lang ]]; then
+		error "License '$lang' does not exist"
+		exit 10
+	fi
 
 	return 0
 }
@@ -310,67 +320,64 @@ get_license() {
 #==============================================================================
 
 get_language() {
-	printf 'Chose a name for the file (spaces will be removed) -- '
-	read -r l_name
+	read -p 'Chose a name for the file (spaces will be removed) -- '
 
-	[[ -z "$l_name" ]] && (
-	error 'Cannot leave file name empty'
-	exit 7
-)
+	if [[ -z "$REPLY" ]]; then
+		error 'Cannot leave file name empty'
+		exit 7
+	fi
 
-l_name="$(echo "$l_name" | tr -d ' ' | head -c250)"
+	l_name="$(echo "$REPLY" | tr -d ' ' | head -c250)"
 
-depend 'cp'
-check_valid_language "$1"
+	depend 'cp'
+	check_valid_language "$1"
 
-user_language="$(echo "$1" | sed "$LANGUAGE_SED")"
+	user_language="$(echo "$1" | sed "$LANGUAGE_SED")"
 
-if [[ ! -f "$LANGUAGE_DIR"/"$user_language" ]]; then
-	error "No language by the name of '$user_language'"
-	list_languages
-	error 'Use one of the above'
+	if [[ ! -f "$LANGUAGE_DIR"/"$user_language" ]]; then
+		error "No language by the name of '$user_language'"
+		list_languages
+		error 'Use one of the above'
 
-	exit 5
-elif [[ -f "$l_name" ]]; then
-	printf 'This file already exists, do you want to overwrite it? [y/N] '
-	read -r yn
+		exit 5
+	elif [[ -f "$l_name" ]]; then
+		read -p 'This file already exists, do you want to overwrite it? [y/N] '
 
-	[[ "$yn" != 'y' ]] && exit
-	printf '	Last chance you can not go back from here? [y/N] '
-	read -r lc
+		[[ $REPLY == y ]] || exit
+		read -p '	Last chance you can not go back from here? [y/N] '
 
-	[[ ! "$lc" = "y" ]] && exit
-fi
+		[[ $REPLY == y ]] || exit
+	fi
 
-cp -rfL "$LANGUAGE_DIR"/"$user_language" "$l_name"
+	cp -rfL "$LANGUAGE_DIR"/"$user_language" "$l_name"
 
-sed -i "$l_name" \
-	-e "s/{{PROJECT_NAME}}/$(sed_escape "$(basename "$l_name")")/g" \
-	-e "s/{{AUTHOR_WEBSITE}}/$(sed_escape "$AUTHOR_WEBSITE")/g" \
-	-e "s/{{CURRENT_DATE}}/$(sed_escape "$(date '+%a %d %B %Y, %I:%M:%S %P (%Z)')")/g" \
-	-e "s/{{AUTHOR_EMAIL}}/$(sed_escape "$AUTHOR_EMAIL")/g" \
-	-e "s/{{AUTHOR_NAME}}/$(sed_escape "$AUTHOR_NAME")/g" \
-	-e "s/{{AUTHOR_GIT}}/$(sed_escape "$AUTHOR_GIT")/g"
+	sed -i "$l_name" \
+		-e "s/{{PROJECT_NAME}}/$(sed_escape "$(basename "$l_name")")/g" \
+		-e "s/{{AUTHOR_WEBSITE}}/$(sed_escape "$AUTHOR_WEBSITE")/g" \
+		-e "s/{{CURRENT_DATE}}/$(sed_escape "$(date '+%a %d %B %Y, %I:%M:%S %P (%Z)')")/g" \
+		-e "s/{{AUTHOR_EMAIL}}/$(sed_escape "$AUTHOR_EMAIL")/g" \
+		-e "s/{{AUTHOR_NAME}}/$(sed_escape "$AUTHOR_NAME")/g" \
+		-e "s/{{AUTHOR_GIT}}/$(sed_escape "$AUTHOR_GIT")/g"
 
-editor="${EDITOR:-}"
+	editor="${EDITOR:-}"
 
-if [[ -z "$editor" ]]; then
-	printf 'Editor to open file in -- '
-	read -r editor
-fi
+	if [[ -z "$editor" ]]; then
+		printf 'Editor to open file in -- '
+		read -r editor
+	fi
 
-[[ -z "$editor" ]] && (
-error 'Cannot leave editor empty'
-exit 8
-)
+	if [[ -z "$editor" ]]; then
+		error 'Cannot leave editor empty'
+		exit 8
+	fi
 
-depend "$(basename "$editor" | awk '{print $1}')"
+	depend "$(basename "$editor")"
 
-set -x
-$editor "$l_name"
-set +x
+	set -x
+	$editor "$l_name"
+	set +x
 
-info "Current language for $l_name is now set to $user_language"
+	info "Current language for $l_name is now set to $user_language"
 }
 
 #=== FUNCTION =================================================================
@@ -487,7 +494,7 @@ templating_help() {
 
 list_types() {
 	printf "language
-	license"
+license"
 
 }
 
@@ -501,79 +508,75 @@ new_template() {
 		FZF_DEFAULT_OPTS='' fzf --layout=reverse --height=20 --no-mouse -i || echo '')"
 
 	if [[ "$type" == "license" ]]; then
-		printf 'License name/alias (spaces will be removed) -- '
-		read -r ln
+		read -p 'License name/alias (spaces will be removed) -- '
 
-		[[ -z "$ln" ]] && (
-		error 'Cannot leave license name empty'
-		exit 7
-	)
+		if [[ -z "$REPLY" ]]; then
+			error 'Cannot leave language name empty'
+			exit 7
+		fi
 
-	ln="$LICENSE_DIR/$(echo "$ln" | tr -d ' ' | head -c250)"
+		ln="$LICENSE_DIR/$(echo "$REPLY" | tr -d ' ' | head -c250)"
 
-	if [[ -f "$ln" ]]; then
-		printf 'This license already exists, do you want to overwrite it? [y/N] '
-		read -r yn
+		if [[ -f "$ln" ]]; then
+			read -p 'This license already exists, do you want to overwrite it? [y/N] '
 
-		[[ "$yn" != 'y' ]] && exit
-	fi
+			[[ $REPLY == y ]] || exit
+		fi
 
-	editor="${EDITOR:-}"
+		editor="${EDITOR:-}"
 
-	if [[ -z "$editor" ]]; then
-		printf 'Editor to open file in -- '
-		read -r editor
-	fi
+		if [[ -z "$editor" ]]; then
+			printf 'Editor to open file in -- '
+			read -r editor
+		fi
 
-	[[ -z "$editor" ]] && (
-	error 'Cannot leave editor empty'
-	exit 8
-)
+		if [[ -z "$editor" ]]; then
+			error 'Cannot leave editor empty'
+			exit 8
+		fi
 
-depend "$(basename "$editor" | awk '{print $1}')"
+		depend "$(basename "$editor" | awk '{print $1}')"
 
-set -x
-$editor "$ln"
-set +x
+		set -x
+		$editor "$ln"
+		set +x
 
-[[ -f "$ln" ]] && einfo "License '$(basename "$ln")' saved"
-elif [[ "$type" == "language" ]]; then
-	printf 'Language name/alias (spaces will be removed) -- '
-	read -r ln
+		[[ -f "$ln" ]] && einfo "License '$(basename "$ln")' saved"
 
-	[[ -z "$ln" ]] && (
-	error 'Cannot leave language name empty'
-	exit 7
-)
+	elif [[ "$type" == "language" ]]; then
+		read -p 'Language name/alias (spaces will be removed) -- '
 
-ln="$LANGUAGE_DIR/$(echo "$ln" | tr -d ' ' | head -c250)"
+		if [[ -z "$REPLY" ]]; then
+			error 'Cannot leave language name empty'
+			exit 7
+		fi
+		ln="$LANGUAGE_DIR/$(echo "$REPLY" | tr -d ' ' | head -c250)"
 
-if [[ -f "$ln" ]]; then
-	printf 'This language already exists, do you want to overwrite it? [y/N] '
-	read -r yn
+		if [[ -f "$ln" ]]; then
+			read -p 'This language already exists, do you want to overwrite it? [y/N] '
 
-	[[ "$yn" != 'y' ]] && exit
-fi
+			[[ $REPLY == y ]] || exit
+		fi
 
-editor="${EDITOR:-}"
+		editor="${EDITOR:-}"
 
-if [[ -z "$editor" ]]; then
-	printf 'Editor to open file in -- '
-	read -r editor
-fi
+		if [[ -z "$editor" ]]; then
+			printf 'Editor to open file in -- '
+			read -r editor
+		fi
 
-[[ -z "$editor" ]] && (
-error 'Cannot leave editor empty'
-exit 8
-)
+		if [[ -z "$editor" ]]; then
+			error 'Cannot leave editor empty'
+			exit 8
+		fi
 
-depend "$(basename "$editor" | awk '{print $1}')"
+		depend "$(basename "$editor" | awk '{print $1}')"
 
-set -x
-$editor "$ln"
-set +x
+		set -x
+		$editor "$ln"
+		set +x
 
-[[ -f "$ln" ]] && einfo "Language '$(basename "$ln")' saved"
+		[[ -f "$ln" ]] && einfo "Language '$(basename "$ln")' saved"
 	fi
 }
 
@@ -593,11 +596,13 @@ delete_license() {
 #==============================================================================
 
 new_config() {
-	einfo "This will overwite your config, are you sure you want do do that?"
-	printf '	[y/N] '
-	read -r yn
+	read -p 'This will overwite your config, are you sure you want do do that? [y/N]'
 
-	[[ "$yn" != 'y' ]] && exit
+	[[ $REPLY == y ]] || exit
+
+	read -p 'This language already exists, do you want to overwrite it? [y/N] '
+
+	[[ $REPLY == y ]] || exit
 
 	make_new_config
 	info 'New config made and saved'
